import Head from "next/head";
import Image from "next/image";
import { Box, Heading, Input, Button, Flex, useToast } from "@chakra-ui/react";
import router from "next/dist/client/router";
import axios from "axios";
import { useState } from "react";
import { jsx } from "@emotion/react";

export default function Home() {
  // axios.get('http://f0374b8f3a79.ngrok.io/api/users/')
  // .then(({data}) => {
  //   console.log(data)
  // })
  // .catch((error) => {
  //   console.log(error)
  // })

  const toast = useToast();

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  if (typeof window !== "undefined") {
    // set localstore value
    let storage = window.localStorage;

    let login = () => {
      // Post method
      // test@gmail.com / 123

      axios({
        method: "post",
        url: "http://localhost:8080/api/users/login",
        data: {
          email: email,
          password: password,
        },
      })
        .then(function (res) {
          console.log(res);
          if (res.data !== "") {
            storage.user = JSON.stringify(res.data);

            toast({
              title: "Success",
              description: "Redirect to dashboard. Please wait",
              status: "success",
              duration: 3000,
              isClosable: true,
            });

            setInterval(function () {
              router.push("/dashboard");
            }, 4000);
          } else {
            toast({
              title: "Error",
              description: "please input again",
              status: "error",
              duration: 9000,
              isClosable: true,
            });
          }
        })
        .catch(function (error) {
          console.log(error);
          toast({
            title: "Error.",
            description: "please input again",
            status: "error",
            duration: 9000,
            isClosable: true,
          });
        });
    };

    return (
      <Box flex="1">
        <Head>
          <title>Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Flex flexDir="column" mt="5rem">
          <Heading textAlign="center">Welcome</Heading>

          <Input
            placeholder="Account"
            mt="1rem"
            onChange={(e) => {
              setEmail(e.target.value);
            }}
          />

          <Input
            placeholder="Password"
            mt="1rem"
            onChange={(e) => {
              setPassword(e.target.value);
            }}
          />

          <Button
            colorScheme="blue"
            mt="1rem"
            onClick={() => {
              login();
            }}
          >
            Login
          </Button>

          <Box mt="1rem" textAlign="right">
            need sign up? click
            <Box
              cursor="pointer"
              as="span"
              onClick={() => router.push("/signup")}
              _hover={{ color: "blue" }}
            >
              {" "}
              here
            </Box>
          </Box>
        </Flex>
      </Box>
    );
  } else {
    return <></>;
  }
}
