import Head from "next/head";
import Image from "next/image";
import { Box, Heading, Input, Button, Flex, useToast } from "@chakra-ui/react";
import router from "next/dist/client/router";
import axios from "axios";
import { useState } from "react";
const Signup = () => {
  const toast = useToast();


    const [name, setName] = useState("");
    const [email, setEmail] = useState("");
    const [tel, setTel] = useState("");
    const [job, setJob] = useState("");
    const [age, setAge] = useState("");
    const [password, setPassword] = useState("");

  let sign = () => {


    axios({
      method: "post",
      url: " http://localhost:8080/api/users/",
      data: {
        name:name,
        email: email,
        telephone:tel,
        job:job,
        age:age,
        password: password,
      },
    })
      .then(function (res) {
        console.log(res);
        if (res.data !== "") {
          toast({
            title: "Success",
            description: "Redirect to login. Please wait",
            status: "success",
            duration: 3000,
            isClosable: true,
          });

          setInterval(function () {
            router.push("/");
          }, 4000);
        } else {
          toast({
            title: "Error",
            description: "please input again",
            status: "error",
            duration: 9000,
            isClosable: true,
          });
        }
      })
      .catch(function (error) {
        console.log(error);
        toast({
          title: "Error.",
          description: "please input again",
          status: "error",
          duration: 9000,
          isClosable: true,
        });
      });
  };

  return (
    <Box flex="1">
      <Head>
        <title>Signup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex flexDir="column" mt="5rem">
        <Heading textAlign="center">Welcome</Heading>

        <Input
          placeholder="Name"
          mt="1rem"
          onChange={(e) => {
            setName(e.target.value);
          }}
        />

        <Input
          placeholder="Email"
          mt="1rem"
          onChange={(e) => {
            setEmail(e.target.value);
          }}
        />

        <Input
          placeholder="Telephone"
          mt="1rem"
          onChange={(e) => {
            setTel(e.target.value);
          }}
        />

        <Input
          placeholder="Job"
          mt="1rem"
          onChange={(e) => {
            setJob(e.target.value);
          }}
        />

        <Input
          placeholder="Age"
          mt="1rem"
          onChange={(e) => {
            setAge(e.target.value);
          }}
        />

        <Input
          placeholder="Password"
          mt="1rem"
          onChange={(e) => {
            setPassword(e.target.value);
          }}
        />

        <Button colorScheme="blue" mt="1rem" onClick={()=>{
          sign()
        }}>
          Sign Up
        </Button>

        <Box mt="1rem" textAlign="right">
          need login? click
          <Box
            cursor="pointer"
            as="span"
            onClick={() => router.push("/")}
            _hover={{ color: "blue" }}
          >
            {" "}
            here
          </Box>
        </Box>
      </Flex>
    </Box>
  );
};

export default Signup;
